name: 'Checkout Code'
description: 'Checkout the code from the repository'
inputs:
    include-super-linter:
        description: 'boolean variable to enable/disable linting' 
        required: false
        type: boolean
        default: false 

runs:
 using: 'composite'
 steps:
   - name: checkout code
     if: ${{ inputs.include-super-linter == 'false' }}
     uses: actions/checkout@v4

   - name: Checkout code for super linter
     if: ${{ inputs.include-super-linter == 'true' }}
     uses: actions/checkout@v4
     with:
        fetch-depth: 0 
